name: POI CI/CD

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml
  pull_request:
    branches: [ main ]

env: 
  poi_path: apis/poi/**
    
jobs:
  build-test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install Dependencies 
      run: dotnet restore apis/poi/web/*.csproj
      
#     - name: Restore dependencies
#       run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore apis/poi/web/*.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal #apis/poi/tests/UnitTests
      
      #### THIS IS OPTIONAL BUT GOOD TO HAVE, CREATE AN ISSUE IF THE JOB FAILS ####
      
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
