name: Trips CI/CD Go Lang

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths: 
      - apis/trips/**
      - .github/workflows/poi.yml
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install dependencies
      run: go get

    - name: Test
      run: go test ./tests
      
#      - name: Build
#       run: go build -v ./...

